// src/styles/palette.ts

export const PALETTE = {
  purple: {
    main: "#6C63FF",
    hover: "#5a52e0",
  },
  slate: {
    accent: "#475569",
    accentLight: "#94a3b8",
    accentDark: "#1e293b",
    surface: "#ffffff",
    surfaceRaised: "#f8fafc",
    surfaceSunken: "#f1f5f9",
    textPrimary: "#0f172a",
    textSecondary: "#334155",
    textMuted: "#94a3b8",
    textOnAccent: "#ffffff",
    border: "#e2e8f0",
    borderStrong: "#cbd5e1",
  },
  ocean: {
    accent: "#0284c7",
    accentLight: "#38bdf8",
    accentDark: "#0c4a6e",
    surface: "#ffffff",
    surfaceRaised: "#f0f9ff",
    surfaceSunken: "#e0f2fe",
    textPrimary: "#0c4a6e",
    textSecondary: "#075985",
    textMuted: "#7dd3fc",
    textOnAccent: "#ffffff",
    border: "#bae6fd",
    borderStrong: "#7dd3fc",
  },
  ember: {
    accent: "#dc2626",
    accentLight: "#f87171",
    accentDark: "#7f1d1d",
    surface: "#ffffff",
    surfaceRaised: "#fff7f7",
    surfaceSunken: "#fee2e2",
    textPrimary: "#1a0000",
    textSecondary: "#7f1d1d",
    textMuted: "#fca5a5",
    textOnAccent: "#ffffff",
    border: "#fecaca",
    borderStrong: "#f87171",
  },
  white: "#ffffff",
} as const;
